import { Controller, Get } from '@nestjs/common';

import { AppService } from './app.service.js';

const matrixSize = 80;
@Controller()
export class AppController {
    constructor(private readonly appService: AppService) {}
    /*
        TODO [LVL1]: Implement API endpoint "GET /" which outputs matrix generated by method generateMatrix and transformed using method matrixToString
        The response should be JSON { matrix: <string> };
    */
    @Get('/')
    getMatrix() {
        const matrix = this.appService.generateMatrix(matrixSize);
        const matrixString = this.appService.matrixToString(matrix);
        return { matrix: matrixString };
    }

    /*
        TODO [LVL2]: The endpoint should be able to accept `seed` numeric query parameter and it will cache the generated matrix based on this parameter
        Hint: You can either test this from postman/insomnia, or implement logic around this also on frontend
        You can use @apify/datastructures LRU Cache for the storage. @see https://github.com/apify/apify-shared-js/blob/master/packages/datastructures/src/lru_cache.ts
        Don't forget to validate and convert the type of the seed param, it needs to be a number.
    */
}
